import { ToolConfig, ToolId } from "@/types";

export const TOOL_CONFIG: Record<ToolId, ToolConfig> = {
  "profile-personality": {
    id: "profile-personality",
    name: "What Your Profile Says About You",
    price: 200,
    emoji: "😮",
    tagline: "Discover what your Instagram reveals about your personality",
    description: "Turn your profile vibe into a warm personality reading you can share.",
    fields: [
      { id: "username", label: "Instagram username", type: "text", required: true, placeholder: "@yourhandle" },
      { id: "bio", label: "Bio text", type: "textarea", required: true, placeholder: "Paste your bio..." },
      {
        id: "captions",
        label: "Last 3 caption examples",
        type: "textarea",
        required: true,
        placeholder: "Caption 1\nCaption 2\nCaption 3",
      },
    ],
  },
  "crush-compatibility": {
    id: "crush-compatibility",
    name: "Are You Compatible With Your Crush?",
    price: 300,
    emoji: "💘",
    tagline: "Find out your compatibility score and what to say tonight",
    description: "A sweet, hopeful compatibility check with a copy-paste message idea.",
    fields: [
      { id: "your_name", label: "Your name", type: "text", required: true },
      { id: "crush_name", label: "Crush's name", type: "text", required: true },
      { id: "your_words", label: "Describe yourself in 3 words", type: "text", required: true },
      { id: "crush_words", label: "Describe your crush in 3 words", type: "text", required: true },
      { id: "how_met", label: "How did you meet?", type: "textarea", required: true },
    ],
  },
  "facebook-prediction": {
    id: "facebook-prediction",
    name: "Your 2026 Prediction",
    price: 500,
    emoji: "🔮",
    tagline: "AI reads your Facebook energy and predicts your 2026",
    description: "Mystical, uplifting 2026 predictions based on your recent post energy.",
    fields: [
      { id: "name", label: "Your name", type: "text", required: true },
      { id: "posts", label: "Paste 5-10 recent Facebook posts", type: "textarea", required: true },
      { id: "city", label: "City / State", type: "text", required: true },
    ],
  },
  "profile-impression": {
    id: "profile-impression",
    name: "What Strangers Think of Your Profile",
    price: 200,
    emoji: "🕵️",
    tagline: "Honest first impression analysis of your Instagram",
    description: "Learn how your profile feels in first 3 seconds and how to upgrade it.",
    fields: [
      { id: "username", label: "Instagram username", type: "text", required: true },
      { id: "bio", label: "Bio text", type: "textarea", required: true },
      {
        id: "aesthetic",
        label: "Profile aesthetic",
        type: "select",
        required: true,
        options: ["Minimal", "Colorful", "Foodie", "Travel", "Lifestyle", "Mixed"],
      },
    ],
  },
  "decode-message": {
    id: "decode-message",
    name: "Decode Your Crush's Message",
    price: 300,
    emoji: "💬",
    tagline: "Find out what they really meant and what to reply",
    description: "Decode mixed signals with calm, kind insight and a confident reply.",
    fields: [
      { id: "your_name", label: "Your name", type: "text", required: true },
      { id: "crush_name", label: "Crush's name", type: "text", required: true },
      { id: "message", label: "Their last message", type: "textarea", required: true },
      {
        id: "reply_time",
        label: "How long did they take to reply?",
        type: "select",
        required: true,
        options: ["Few minutes", "1-3 hours", "Same day", "1 day", "2+ days"],
      },
      {
        id: "context",
        label: "Relationship status",
        type: "select",
        required: true,
        options: ["Just met", "Talking for a while", "Used to date", "Old friends"],
      },
    ],
  },
  "friendship-roast": {
    id: "friendship-roast",
    name: "Your Friendship Roast",
    price: 100,
    emoji: "😂",
    tagline: "Savage but loving roast to share with your bestie",
    description: "A playful roast that feels hilariously true but always affectionate.",
    fields: [
      { id: "your_name", label: "Your name", type: "text", required: true },
      { id: "friend_name", label: "Best friend's name", type: "text", required: true },
      {
        id: "years",
        label: "How long have you been friends?",
        type: "select",
        required: true,
        options: ["< 1 year", "1-2 years", "3-5 years", "6-10 years", "10+ years"],
      },
      {
        id: "signature_thing",
        label: "One thing your friend always does",
        type: "text",
        required: true,
      },
    ],
  },
  "instagram-type": {
    id: "instagram-type",
    name: "What Kind of Instagram Person Are You?",
    price: 200,
    emoji: "🧬",
    tagline: "Find your Instagram personality type",
    description: "Answer 5 quick questions and discover your Instagram archetype.",
    fields: [
      { id: "frequency", label: "How often do you post?", type: "radio", required: true, options: ["Daily", "Few times a week", "Rarely", "Only stories"] },
      { id: "content", label: "What do you mostly post?", type: "radio", required: true, options: ["Food", "Travel", "Selfies", "Reels", "Random", "Nothing"] },
      { id: "stories", label: "How many stories do you watch silently?", type: "radio", required: true, options: ["None", "A few", "So many", "All of them"] },
      { id: "typo", label: "What if you spot a typo later?", type: "radio", required: true, options: ["Delete and repost", "Leave it", "Panic", "What typo"] },
      { id: "description", label: "Your Instagram is best described as:", type: "radio", required: true, options: ["Aesthetic", "Chaotic", "Private", "Abandoned"] },
    ],
  },
};

export const TOOLS = Object.values(TOOL_CONFIG);
