import Link from "next/link";

export default function TermsAndConditionsPage() {
  return (
    <main className="min-h-screen px-4 py-6">
      <div className="rvm-card mx-auto max-w-md rounded-2xl p-5">
        <Link href="/" className="text-sm font-semibold text-[#007a70]">
          ← Back to Home
        </Link>
        <h1 className="mt-3 text-2xl font-bold text-[#0a3030]">Terms and Conditions</h1>
        <p className="mt-1 text-sm text-[#6aabab]">Last updated: March 2026</p>

        <div className="mt-4 space-y-3 text-sm leading-relaxed text-[#0a3030]">
          <p>
            By using ReadMyVibe, you agree to these terms. ReadMyVibe provides AI-generated entertainment readings and
            insights intended for fun and personal use.
          </p>
          <p>
            You must provide accurate input details and use the platform lawfully. You must not use abusive, illegal, or
            harmful content.
          </p>
          <p>
            Readings are generated by AI and are not professional, legal, medical, or financial advice. Please use your own
            judgment.
          </p>
          <p>
            Prices are shown per tool before payment. Access to paid sections is granted after successful payment verification.
          </p>
          <p>
            We may update tools, prices, and features at any time to improve service quality.
          </p>
          <p>
            If you do not agree with these terms, please do not use the platform.
          </p>
        </div>
      </div>
    </main>
  );
}
